In [1]:
import torch
torch.__version__

# 1. Introduction to tensors

What is a tensor? A `tensor` based on the documentation of PyTorch is a multi-dimensional matrix containing elements of single data type.

https://pytorch.org/docs/stable/tensors.html

To initialize a tensor in PyTorch we usualy use `torch.empty()` or `torch.tensor()` methods.

Let's start with a scalar. A scalar is a single number and in the Machine Learning world it is actually a zero dimension tensor. To put it more simply, it is a tensor that has a single number

###  1.1 How to initialize tensors
Initialize a scalar with pytorch:

In [9]:
x = torch.empty(1) 
x

tensor([-0.0001])

Initialize a tensor with 3 numbers in one dimension (Vector):

In [11]:
x = torch.empty(3) 
x

tensor([-1.2719e-04,  4.5640e-41,  6.7474e-35])

Initialize empty tensor with 2 dimensions:
- The first dimension (dimension 0) will have 2 rows.
- The second dimension (dimension 1) will have 3 numbers (or columns).

In [12]:
x = torch.empty(2,3) 
x

tensor([[8.5927e-35, 0.0000e+00, 0.0000e+00],
        [1.1755e-38, 3.7651e-38, 0.0000e+00]])

Initialize a tensor with three dimensions or more:

In [14]:
x = torch.empty(2,3, 3) 
y = torch.empty(2,3,4,5)
x, y

(tensor([[[-1.2719e-04,  4.5640e-41,  8.5364e-35],
          [ 0.0000e+00,  6.9269e-35,  0.0000e+00],
          [ 8.5726e-35,  0.0000e+00,  0.0000e+00]],
 
         [[ 0.0000e+00,  8.5748e-35,  0.0000e+00],
          [ 9.6461e-36,  0.0000e+00, -1.9511e+04],
          [ 4.5639e-41,  1.4013e-45,  0.0000e+00]]]),
 tensor([[[[ 1.4013e-45,  0.0000e+00,  8.5895e-35,  0.0000e+00,  8.5898e-35],
           [ 0.0000e+00,  1.4013e-45,  0.0000e+00,  8.5895e-35,  0.0000e+00],
           [ 8.5895e-35,  0.0000e+00,  3.3631e-44,  0.0000e+00,  1.3784e-38],
           [ 0.0000e+00,  2.8026e-45,  1.5414e-44,  0.0000e+00,  0.0000e+00]],
 
          [[ 2.8026e-45,  0.0000e+00,  2.8026e-45,  1.4013e-45,  3.3631e-44],
           [        nan, -2.5375e-06,  4.5640e-41,  1.4013e-45,  0.0000e+00],
           [ 1.4013e-45,  1.4013e-45,  2.8026e-45,  5.6052e-45,  2.8026e-45],
           [ 1.2612e-44,  2.9427e-44,  0.0000e+00,  8.5895e-35,  0.0000e+00]],
 
          [[ 1.2749e-38,  0.0000e+00,  1.4013e-45,  1.4013

In PyTorch and Machine Learning is particularly useful sometimes to initialize a tensor with zeros. In pytorch we do that using `torch.zeros()` in the same way we were using `empty()`:

In [17]:
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Also in Pytorch we can initialize a tensor with random values using `torch.rand()`:

In [19]:
x = torch.rand(3,2)
x

tensor([[0.5446, 0.2886],
        [0.9925, 0.2873],
        [0.1601, 0.4598]])

We can also create a tensor from numpy array or a python array (list)

Initialize from numpy:

In [32]:
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy Array:")
print(numpy_array)

NumPy Array:
[[1 2 3]
 [4 5 6]]


In [35]:
tensor_from_numpy = torch.from_numpy(numpy_array)
print("PyTorch Tensor from NumPy Array:")
print(tensor_from_numpy)

PyTorch Tensor from NumPy Array:
tensor([[1, 2, 3],
        [4, 5, 6]])


Initialize from python list:

In [36]:
python_list = [[1, 2, 3], [4, 5, 6]]
print("Python List:")
print(python_list)

Python List:
[[1, 2, 3], [4, 5, 6]]


In [37]:
tensor_from_list = torch.tensor(python_list)
print("PyTorch Tensor from Python List:")
print(tensor_from_list)

PyTorch Tensor from Python List:
tensor([[1, 2, 3],
        [4, 5, 6]])


### 1.2 Tensors and their attributes (methods)

**Size, shape and ndim of a Tensor**:

The size() method and the shape method returns the same thing with the difference that the size can get a dimension as a parameter and give you the size of a tensor at a specific dimension.

The ndim is the number of Tensor Dimensions

In [20]:
x.shape

torch.Size([3, 2])

In [21]:
x.size()

torch.Size([3, 2])

Access specific dimension's size

In [26]:
x.size(0)

3

In [27]:
x.size(1)

2

Number of dimensions: You can get the number of dimensions for a tensor by running ndim

In [22]:
x.ndim

2

Tensors can have only 1 data type for all the elements inside a tensor. You can get the data type by running `tensor_x.dtype`

In [29]:
print(x.dtype)

torch.float32


**How to specify types in PyTorch**

You can set the dtype of a PyTorch tensor at creation or initialization, **e.g.,** `torch.tensor(..., dtype=torch.float32)`.

Lets initialize a tensor of type torch.float16

In [41]:
numpy_array = np.array([[2,3],[3,4]])
x = torch.tensor(numpy_array, dtype=torch.float16)
print(f'tensor: {x}')
print(f'data type: {x.dtype}')

tensor: tensor([[2., 3.],
        [3., 4.]], dtype=torch.float16)
data type: torch.float16


**Gradients and Pytorch Tensors**

In PyTorch in order to calculate the gradients for a tensor when performing backpropagation, the tensor must have the `require_grad` set to `True`

In the example bellow we show that PyTorch gives you an error if you try to instantiate a torch tensor without a torch.dtype or if the tensor is not of type complex and float you will get an error

In [47]:
x = torch.tensor(numpy_array, requires_grad=True)
print(x)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [49]:
x = torch.tensor(numpy_array, dtype=torch.int8, requires_grad=True)
print(x)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [51]:
x = torch.tensor(numpy_array, dtype=torch.float16, requires_grad=True)
y = torch.tensor(numpy_array, dtype=torch.complex64, requires_grad=True)
print(x)
print(y)

tensor([[2., 3.],
        [3., 4.]], dtype=torch.float16, requires_grad=True)
tensor([[2.+0.j, 3.+0.j],
        [3.+0.j, 4.+0.j]], requires_grad=True)


### 1.3 Basic Operations on tensors with PyTorch

In PyTorch we can perform various operations with Tensors:
- Element-wise operations
- Slicing tensors
- Reshape tensors

#### 1.3.1 Element-wise operations

In [53]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

Element-wise addition of two tensors

In [55]:
sum_tensor = tensor1 + tensor2
print("Addition:")
print(sum_tensor)

Addition:
tensor([[ 6,  8],
        [10, 12]])


In [58]:
tensor1.add_(tensor2)

tensor([[ 6,  8],
        [10, 12]])

In [59]:
torch.add(tensor1, tensor2)

tensor([[11, 14],
        [17, 20]])

Subtraction:
- tensor1 - tensor2
- torch.sub(tensor1, tensor2)

In [61]:
z = tensor1 - tensor2
z

tensor([[1, 2],
        [3, 4]])

In [62]:
z = torch.sub(tensor1, tensor2)
z

tensor([[1, 2],
        [3, 4]])

Element-wise multiplication of two tensors

In [56]:
tensor_mul = tensor1 * tensor2
print("\nMultiplication (element-wise):")
print(tensor_mul)


Multiplication (element-wise):
tensor([[ 5, 12],
        [21, 32]])


Element-wise square root of **1 tensor**

In [57]:
tensor_sqrt = torch.sqrt(tensor1.float())
print("\nElement-wise Square Root:")
print(tensor_sqrt)


Element-wise Square Root:
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


#### 1.3.2 Slicing Tensors

In [65]:
X = torch.rand(5,5)
X

tensor([[0.0769, 0.3255, 0.0078, 0.1532, 0.6928],
        [0.6082, 0.6499, 0.0732, 0.9209, 0.5639],
        [0.7117, 0.9250, 0.3895, 0.0602, 0.8556],
        [0.8881, 0.8602, 0.6993, 0.6661, 0.3131],
        [0.9130, 0.7370, 0.0197, 0.5863, 0.8647]])

In [69]:
# print all rows and column 0
X[:, 0]

tensor([0.0769, 0.6082, 0.7117, 0.8881, 0.9130])

In [70]:
# print all columns and row 1
X[1, :]

tensor([0.6082, 0.6499, 0.0732, 0.9209, 0.5639])

In [73]:
# print a scalar out of our tensor with 2 dimensions
# call item() on the tensor to get the scalar only
X[1,1], X[1,1].item()

(tensor(0.6499), 0.6499195694923401)

#### 1.3.3 Reshape Tensors

Lets reshape the tensor with x.view

In [87]:
import torch

# Create a 1D tensor with 6 elements
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

# Reshape to a 2D tensor with shape (2, 3)
reshaped_tensor = tensor.view(2, 3)
print("Original Tensor:")
print(tensor)
print("Reshaped Tensor:")
print(reshaped_tensor)

Original Tensor:
tensor([1, 2, 3, 4, 5, 6])
Reshaped Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [88]:
# Create a 2D tensor with shape (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape to a 3D tensor with shape (1, 2, 3)
reshaped_tensor = tensor.view(1, 2, 3)
print("Original Tensor:")
print(tensor)
print("Reshaped Tensor:")
print(reshaped_tensor)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped Tensor:
tensor([[[1, 2, 3],
         [4, 5, 6]]])


### 1.4 Numpy and Tensors

We can convert the tensor to numpy by calling the `numpy()` method on the tensor object.

In [99]:
# torch to numpy
tensor = torch.rand(5)
np_array = tensor.numpy()
type(np_array), np_array

(numpy.ndarray,
 array([0.88024426, 0.45601016, 0.7569838 , 0.7983077 , 0.01635176],
       dtype=float32))

One thing we need to be always careful is that if the tensor is on the CPU (and not on GPU) then both objects will share the same memory location

In [100]:
tensor.add_(1), np_array

(tensor([1.8802, 1.4560, 1.7570, 1.7983, 1.0164]),
 array([1.8802443, 1.4560101, 1.7569838, 1.7983077, 1.0163517],
       dtype=float32))

Again we can do this vice versa and call `torch.from_numpy(np_array)` or `torch.tensor(np_array)`. 

The big difference is that `torch.tensor` will create an actual copy of the numpy array, however the `torch.from_numpy` will share the same memory

In [102]:
np_array = np.ones(2)
tensor_from_numpy = torch.from_numpy(np_array)
tensor = torch.tensor(np_array)

print(np_array)
print(tensor_from_numpy)
print(tensor)

np_array += 5
print(np_array)
print(tensor_from_numpy)
print(tensor)

[1. 1.]
tensor([1., 1.], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
[6. 6.]
tensor([6., 6.], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)


### 1.5 Tensors and Device (GPU, CPU)

In PyTorch all the tensor are stored on CPU by default. 

However, what we can do is move the specific tensor we want on the GPU and utilize the accelerated computing that CUDA provides to us.

To do that we use tensor.to(specific_device):

In [105]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor_on_cpu = torch.rand(2,3)
print(tensor_on_cpu)

tensor = torch.rand(5,5)
print(tensor.to(device))

tensor([[0.8598, 0.6049, 0.6071],
        [0.0232, 0.1727, 0.7790]])
tensor([[0.2614, 0.8924, 0.4112, 0.8370, 0.6593],
        [0.0612, 0.7187, 0.0878, 0.7994, 0.3717],
        [0.7681, 0.5410, 0.4325, 0.5168, 0.1549],
        [0.1903, 0.4956, 0.7716, 0.2225, 0.7799],
        [0.5253, 0.3374, 0.8353, 0.9044, 0.7633]], device='cuda:0')


To directly create them on the desired device we can use:

In [106]:
torch.rand(5,5, device=device)

tensor([[0.5251, 0.8401, 0.6055, 0.3960, 0.2198],
        [0.9747, 0.4732, 0.7296, 0.1378, 0.1920],
        [0.3938, 0.8352, 0.2934, 0.0880, 0.8944],
        [0.1644, 0.1350, 0.6425, 0.9477, 0.4038],
        [0.2498, 0.5694, 0.2893, 0.2022, 0.5288]], device='cuda:0')