In [1]:
import torch

PyTorch provides a variety of functions for creating new tensors prepopulated with values. For example, by invoking arange(n), we can create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included). By default, the interval size is 1. Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based computation.

In [2]:
x = torch.arange(12, dtype=torch.float32)
x, x.shape, x.ndim

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]),
 1)

With tensor.numel we can see the number of elements in each dimension.

In [7]:
x.numel()

12

In [8]:
X = x.reshape(4, 3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [9]:
X = x.reshape(4, -1)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [11]:
torch.zeros((2, 3, 5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 9))

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

We often wish to sample each element randomly (and independently) from a given probability distribution. For example, the parameters of neural networks are often initialized randomly. The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.

In [13]:
torch.randn(3, 4)

tensor([[-0.3044,  2.6649,  0.6353, -0.4530],
        [-0.2154, -1.6241,  0.9213, -0.5267],
        [-0.8124, -0.5973, -0.2053, -0.1751]])

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing

In [20]:
X[-1], X[1:3]

(tensor([ 9., 10., 11.]),
 tensor([[12., 12., 12.],
         [ 6.,  7.,  8.]]))

In [16]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., 17.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [17]:
X[:2, :] = 12
X

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [18]:
tensor = torch.zeros(4, 3, 4)
tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
tensor[1:3,0:1,0:2] = 1
tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])